# Generated by Django 4.2.4 on 2023-08-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chainlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chainlinkmanager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
