# Generated by Django 4.2.4 on 2023-08-09 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', tinymce.models.HTMLField()),
                ('photo', models.ImageField(blank=True, upload_to='idea_image/')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chain.chain')),
                ('current_chain_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chain.chainlink')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject')], max_length=10)),
                ('is_author_reject_his_idea', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_chain_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_idea_movements', to='chain.chainlink')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.idea')),
                ('manager_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chain.chainlinkmanager')),
                ('next_chain_link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_idea_movements', to='chain.chainlink')),
            ],
        ),
    ]
